### PR TITLE
schema updates

### PR DESCRIPTION
**Pull request by kthrog**
Pushing tested/confirmed schema changes to prod; now shows GFF as fundingAgency option

Note: new parser works -- now takes 3 minutes!! lots of schema updates coming soon now that this is the case :)

### CODE REVIEW

**Comment by allaway** [comment]
That's awesome! I will update develop to include the new parser, then.

**Review by allaway — CHANGES_REQUESTED** [review]
Can you rename the new jsonld file to `NF.jsonld` in the config and in the filename itself? That will make it easier to inspect the diff between the old and new schema (though it may still be too large to really comprehend, we'll see!)

**Comment by kthrog** [comment]
The new parser script is currently local on my machine -- but Sujay is finalizing it here: https://github.com/Sage-Bionetworks/schematic/tree/develop-graph-methods if we want go ahead and pull from there. He mentioned he's testing a few more things before pushing it up to the main HTAN_data_curator branch. But I can confirm it worked for us. :)

**Comment by kthrog** [comment]
Rename done! Let me know if that makes the diff clearer.

**Review by allaway — APPROVED** [review]
Thanks! Yes, that makes it a lot easier to review the changes to the json-ld! 
https://github.com/nf-osi/schematic/pull/7/files

LGTM!

**Pull request merged**
